/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CertamesRouteImport } from './routes/certames'
import { Route as IngestaoRouteImport } from './routes/ingestao'
import { Route as MetodologiaRouteImport } from './routes/metodologia'
import { Route as VinculosRouteImport } from './routes/vinculos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CertamesRoute = CertamesRouteImport.update({
  id: '/certames',
  path: '/certames',
  getParentRoute: () => rootRouteImport,
} as any)
const IngestaoRoute = IngestaoRouteImport.update({
  id: '/ingestao',
  path: '/ingestao',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodologiaRoute = MetodologiaRouteImport.update({
  id: '/metodologia',
  path: '/metodologia',
  getParentRoute: () => rootRouteImport,
} as any)
const VinculosRoute = VinculosRouteImport.update({
  id: '/vinculos',
  path: '/vinculos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/certames': typeof CertamesRoute
  '/ingestao': typeof IngestaoRoute
  '/metodologia': typeof MetodologiaRoute
  '/vinculos': typeof VinculosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/certames': typeof CertamesRoute
  '/ingestao': typeof IngestaoRoute
  '/metodologia': typeof MetodologiaRoute
  '/vinculos': typeof VinculosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/certames': typeof CertamesRoute
  '/ingestao': typeof IngestaoRoute
  '/metodologia': typeof MetodologiaRoute
  '/vinculos': typeof VinculosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/certames' | '/ingestao' | '/metodologia' | '/vinculos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/certames' | '/ingestao' | '/metodologia' | '/vinculos'
  id:
    '__root__' | '/' | '/certames' | '/ingestao' | '/metodologia' | '/vinculos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CertamesRoute: typeof CertamesRoute
  IngestaoRoute: typeof IngestaoRoute
  MetodologiaRoute: typeof MetodologiaRoute
  VinculosRoute: typeof VinculosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certames': {
      id: '/certames'
      path: '/certames'
      fullPath: '/certames'
      preLoaderRoute: typeof CertamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingestao': {
      id: '/ingestao'
      path: '/ingestao'
      fullPath: '/ingestao'
      preLoaderRoute: typeof IngestaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodologia': {
      id: '/metodologia'
      path: '/metodologia'
      fullPath: '/metodologia'
      preLoaderRoute: typeof MetodologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vinculos': {
      id: '/vinculos'
      path: '/vinculos'
      fullPath: '/vinculos'
      preLoaderRoute: typeof VinculosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CertamesRoute: CertamesRoute,
  IngestaoRoute: IngestaoRoute,
  MetodologiaRoute: MetodologiaRoute,
  VinculosRoute: VinculosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
